export const SIGNIN = "SIGNIN";
export const SIGNUP = "SIGNUP";
export const SIGNOUT = "SIGNOUT";

//Packages
export const LIST_PACKAGES = "LIST_PACKAGES";
export const LIST_PACKAGE_IDS = "LIST_PACKAGE_IDS";
export const LIST_PACKAGES_FAILURE = "LIST_PACKAGES_FAILURE";
export const ADD_PACKAGE = "ADD_PACKAGE";
export const ADD_PACKAGE_FAILURE = "ADD_PACKAGE_FAILURE";
export const EDIT_PACKAGE = "EDIT_PACKAGE";
export const EDIT_PACKAGE_FAILURE = "EDIT_PACKAGE_FAILURE";

/*--------- Admin Actions ---------*/

//Transfers
export const LIST_TRANSFERS = "LIST_TRANSFERS";
export const LIST_TRANSFERS_FAILURE = "LIST_TRANSFERS_FAILURE";

export const ADD_TRANSFER = "ADD_TRANSFER";
export const EDIT_TRANSFER = "EDIT_TRANSFER";
export const DELETE_TRANSFER = "DELETE_TRANSFER";

//Bespoke tours
export const LIST_INQUIRIES = "LIST_INQUIRIES";
export const LIST_INQUIRIES_FAILURE = "LIST_INQUIRIES_FAILURE";
export const MARK_INQUIRIES = "MARK_INQUIRIES";
export const MARK_INQUIRIES_FAILURE = "MARK_INQUIRIES_FAILURE";
export const ADD_INQUIRY = "ADD_INQUIRY";

//Itinerary
export const LIST_ITINERARIES = "LIST_ITINERARIES";
export const LIST_ITINERARIES_FAILURE = "LIST_ITINERARIES_FAILURE";
export const ADD_ITINERARY = "ADD_ITINERARY";
export const ADD_ITINERARY_FAILURE = "ADD_ITINERARY_FAILURE";
export const EDIT_ITINERARY = "EDIT_ITINERARY";
export const EDIT_ITINERARY_FAILURE = "EDIT_ITINERARY_FAILURE";
